{% set name = "partsegcore-compiled-backend" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PartSegCore_compiled_backend-{{ version }}.tar.gz
  sha256: ef61b5b07c6cb6dc56d0f917d18dea3c7a22739b8a717d4fec1e68a61ef69269

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - cython >=0.29.13
    - numpy >= 1.25
    - pip
    - python >= 3.9
    - setuptools-scm >=3.4
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - PartSegCore_compiled_backend
    - PartSegCore_compiled_backend.multiscale_opening
    - PartSegCore_compiled_backend.color_image_cython
    - PartSegCore_compiled_backend.utils
    - PartSegCore_compiled_backend.sprawl_utils.find_split
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg is a GUI and a library for segmentation algorithms. This is PartSegCore, its compiled backend.
  license: BSD-3-Clause
  license_file: License.txt
  dev_url: https://github.com/4DNucleome/PartSegCore-compiled-backend

extra:
  recipe-maintainers:
    - Czaki
    - goanpeca
