{% set name = "partsegcore-compiled-backend" %}
{% set version = "0.15.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c4940b271c213721912041dc2845781bf76615a5eba0e1ddf9d747d234890cd0

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - make
    - cmake >=3.15
    - cython-cmake
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.13
    - numpy
    - pip
    - python
    - scikit-build-core >=0.2.0
    - setuptools-scm >=8.1
    - cmake
    - cython-cmake
    - make
    - ninja
  run:
    - python

test:
  imports:
    - PartSegCore_compiled_backend
    - PartSegCore_compiled_backend.multiscale_opening
    - PartSegCore_compiled_backend.color_image_cython
    - PartSegCore_compiled_backend.utils
    - PartSegCore_compiled_backend.sprawl_utils.find_split
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg is a GUI and a library for segmentation algorithms. This is PartSegCore, its compiled backend.
  license: BSD-3-Clause
  license_file: License.txt
  dev_url: https://github.com/4DNucleome/PartSegCore-compiled-backend

extra:
  recipe-maintainers:
    - Czaki
    - goanpeca
